#ifndef UPDATE_MESH_ROOT_SIGNATURE_HLSL
#define UPDATE_MESH_ROOT_SIGNATURE_HLSL

// CBVs
#define GLOBAL_CB_BINDING_SLOT CBV_SLOT(0)
#define GEOMETRY_CB_BINDING_SLOT CBV_SLOT(1)
#define UPDATE_CB_BINDING_SLOT CBV_SLOT(2)

// SRVs
#define CURRENT_VERTEX_BUFFER_SLOT SRV_SLOT(0)
#define INDEXED_BISECTOR_BUFFER_BINDING_SLOT SRV_SLOT(1)

// UAVs
// CBT buffers
#define CBT_BUFFER0_BINDING_SLOT UAV_SLOT(0)
#define CBT_BUFFER1_BINDING_SLOT UAV_SLOT(1)

// Bisector buffers
#define HEAP_ID_BUFFER_BINDING_SLOT UAV_SLOT(2)
#define NEIGHBORS_BUFFER_BINDING_SLOT UAV_SLOT(3)
#define NEIGHBORS_OUTPUT_BUFFER_BINDING_SLOT UAV_SLOT(4)

// Intermediate buffers
#define BISECTOR_DATA_BUFFER_BINDING_SLOT UAV_SLOT(5)
#define CLASSIFICATION_BUFFER_BINDING_SLOT UAV_SLOT(6)
#define SIMPLIFICATION_BUFFER_BINDING_SLOT UAV_SLOT(7)
#define ALLOCATE_BUFFER_BINDING_SLOT UAV_SLOT(8)
#define PROPAGATE_BUFFER_BINDING_SLOT UAV_SLOT(9)
#define MEMORY_BUFFER_BINDING_SLOT UAV_SLOT(10)

// Indexation buffers
#define INDIRECT_DISPATCH_BUFFER_BINDING_SLOT UAV_SLOT(11)
#define INDIRECT_DRAW_BUFFER_BINDING_SLOT UAV_SLOT(12)
#define BISECTOR_INDICES_BINDING_SLOT UAV_SLOT(13)
#define VISIBLE_BISECTOR_INDICES_BINDING_SLOT UAV_SLOT(14)
#define MODIFIED_BISECTOR_INDICES_BINDING_SLOT UAV_SLOT(15)

// Debug
#define VALIDATION_BUFFER_BINDING_SLOT UAV_SLOT(16)

// Counters
#define NUM_SRV_BINDING_SLOTS 2
#define NUM_CBV_BINDING_SLOTS 3
#define NUM_UAV_BINDING_SLOTS 17

#endif // UPDATE_MESH_ROOT_SIGNATURE_HLSL